a = int(input("Enter 1st number: "))
b = int(input("Enter 2nd number: "))
print("Addition of this number:", a + b)
print("Subtraction of this number:", a - b)
print("Multiplication of this number:", a * b)
print("Division of this number:", a / b)
print("Modulus of this number:", a % b)
print("Floor division of this number:", a // b)
print("Exponentiation of this number:", a ** b)